spring.application.name=BookingService

server.port = 9092

spring.datasource.url=jdbc:postgresql://localhost:5432/bookservice
spring.datasource.username=postgres
spring.datasource.password=vitthal@2003

spring.jpa.show-sql=true 
spring.jpa.hibernate.ddl-auto=create-drop